# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end

target 'TheMoviesReal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMoviesReal
	pod 'SDWebImage'
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Reusable'
	pod 'AlamofireObjectMapper'
	pod 'NSObject+Rx'
	pod 'MBProgressHUD'
	pod 'Cosmos' 
	pod 'SideMenu'
	pod 'MJRefresh'
	pod 'youtube-ios-player-helper'
	pod 'iCarousel'
	pod 'hpple'
	pod 'Then'
end
